apiVersion: apps/v1
kind: Deployment
metadata:
  name: reputation-service
  namespace: pavi-ns
  labels:
    app: reputation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reputation-service
  template:
    metadata:
      labels:
        app: reputation-service
    spec:
      containers:
      - name: reputation-service
        image: pavithrasambath2003/reputation-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5006
        env:
        - name: PORT
          value: "5006"
        envFrom:
        - configMapRef:
            name: medicojob-config
