apiVersion: v1
kind: Secret
metadata:
  namespace: dev
  name: medicojob-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "pavi"
  MONGO_INITDB_ROOT_PASSWORD: "pavi@123"
  MONGO_URI: "mongodb://pavi:pavi%40123@mongodb:27017/medicojob?authSource=admin"
  MONGO_URI_USER: "mongodb://pavi:pavi%40123@mongodb:27017/medicojob?authSource=admin"
  MONGO_URI_JOB: "mongodb://pavi:pavi%40123@mongodb:27017/medicojob?authSource=admin"
  MONGO_URI_MATCHING: "mongodb://pavi:pavi%40123@mongodb:27017/medicojob?authSource=admin"
  MONGO_URI_AVAILABILITY: "mongodb://pavi:pavi%40123@mongodb:27017/medicojob?authSource=admin"
  MONGO_URI_LOCATION: "mongodb://pavi:pavi%40123@mongodb:27017/medicojob?authSource=admin"
  MONGO_URI_REPUTATION: "mongodb://pavi:pavi%40123@mongodb:27017/medicojob?authSource=admin"
  JWT_SECRET: "super_secret_jwt_key_medicojob_2026"