server {
    listen 80;
    server_name localhost;

    # Serve static files for the React app
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to the api-gateway
    location ~ ^/(auth|jobs|match|availability|location|nearby|reviews|socket\.io) {
        proxy_pass http://api-gateway.pavi-ns.svc.cluster.local:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
