version: "3.8"

services:
  api-gateway:
    container_name: api-gateway-container
    build: ./backend/api-gateway
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      PORT: 5000
      USER_SERVICE_URL: http://user-service:5001
      JOB_SERVICE_URL: http://job-service:5002
      MATCHING_SERVICE_URL: http://matching-service:5003
      AVAILABILITY_SERVICE_URL: http://availability-service:5004
      LOCATION_SERVICE_URL: http://location-service:5005
      REPUTATION_SERVICE_URL: http://reputation-service:5006
    depends_on:
      - user-service
      - job-service
      - matching-service
      - availability-service
      - location-service
      - reputation-service
    restart: always

  user-service:
    container_name: user-service-container
    build: ./backend/user-service
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      PORT: 5001
    restart: always

  job-service:
    container_name: job-service-container
    build: ./backend/job-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      PORT: 5002
    restart: always

  matching-service:
    container_name: matching-service-container
    build: ./backend/matching-service
    ports:
      - "5003:5003"
    env_file:
      - .env
    environment:
      PORT: 5003
    restart: always

  availability-service:
    container_name: availability-service-container
    build: ./backend/availability-service
    ports:
      - "5004:5004"
    env_file:
      - .env
    environment:
      PORT: 5004
    restart: always

  location-service:
    container_name: location-service-container
    build: ./backend/location-service
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      PORT: 5005
    restart: always

  reputation-service:
    container_name: reputation-service-container
    build: ./backend/reputation-service
    ports:
      - "5006:5006"
    env_file:
      - .env
    environment:
      PORT: 5006
    restart: always

  frontend:
    container_name: frontend-container
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    depends_on:
      - api-gateway
    stdin_open: true
    tty: true
    restart: always