apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  labels:
    app: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
      - name: location-service
        image: medicojob-location-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5005
        env:
        - name: PORT
          value: "5005"
        envFrom:
        - configMapRef:
            name: medicojob-config
