apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: pavi-ns
  labels:
    app: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service
        image: pavithrasambath2003/matching-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
        env:
        - name: PORT
          value: "5003"
        envFrom:
        - configMapRef:
            name: medicojob-config
