apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: pavithrasambath2003/api-gateway:v1
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: medicojob-config
        - secretRef:
            name: medicojob-secrets



