apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prod
  name: medicojob-config
data:
  PORT: "5000"
  USER_SERVICE_URL: "http://user-service:5001"
  JOB_SERVICE_URL: "http://job-service:5002"
  MATCHING_SERVICE_URL: "http://matching-service:5003"
  AVAILABILITY_SERVICE_URL: "http://availability-service:5004"
  LOCATION_SERVICE_URL: "http://location-service:5005"
  REPUTATION_SERVICE_URL: "http://reputation-service:5006"
  ENVIRONMENT: "production"

