apiVersion: v1
kind: Secret
metadata:
  namespace: prod
  name: medicojob-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "prodadmin"
  MONGO_INITDB_ROOT_PASSWORD: "prodpassword123!secure"
  MONGO_URI: "mongodb://prodadmin:prodpassword123!secure@mongodb:27017/medicojob?authSource=admin"
  JWT_SECRET: "prod_super_secret_jwt_key_medicojob_2026_secure"

