apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: matching-service
spec:
  type: ClusterIP
  selector:
    app: matching-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003

