apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: pavi-ns
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: pavithrasambath2003/api-gateway:tagname
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: medicojob-config
