namespace: dev
name: api-gateway
replicaCount: 1
image:
  repository: pavithrasambath2003/api-gateway
  tag: v1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000
containerPort: 5000
env:
  PORT: "5000"
httpRoute:
  enabled: false
  gatewayName: medicojob-gateway
  paths: []
serviceAccount:
  create: true
job:
  enabled: false
