apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.2.222
  share: /var/lib/data
volumeBindingMode: Immediate
mountOptions:
  - nolock
