apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-location-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PaviTechDevloper/MedicoJob.git
    targetRevision: main
    path: helm/apps/location-service
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
