namespace: prod
name: reputation-service
replicaCount: 2
image:
  repository: pavithrasambath2003/reputation-service
  tag: v1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5006
containerPort: 5006
env:
  PORT: "5006"
httpRoute:
  enabled: true
  gatewayName: medicojob-gateway
  paths:
    - /reviews
serviceAccount:
  create: true
job:
  enabled: false
