apiVersion: v1
kind: Service
metadata:
  name: availability-service
  namespace: pavi-ns
spec:
  type: ClusterIP
  selector:
    app: availability-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
