namespace: prod
name: availability-service
replicaCount: 2
image:
  repository: ghcr.io/pavitechdevloper/pavitechdevloper.availability_service
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  type: ClusterIP
  port: 5004
containerPort: 5004
configMap:
  enabled: true
  name: medicojob-config
secret:
  enabled: true
  name: medicojob-secrets
env:
  PORT: "5004"
httpRoute:
  enabled: true
  gatewayName: medicojob-gateway
  paths:
    - /availability
serviceAccount:
  create: true
job:
  enabled: false
