apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PaviTechDevloper/MedicoJob.git
    targetRevision: main
    path: opslora-helm/infra/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
