name: Availability Service Pipeline

on:
  workflow_call:

concurrency:
  group: medicojob-availability-service-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/ci_service_pipeline.yml
    with:
      service_name: availability-service
      service_path: backend/availability-service
      sonar_project_key: medicojob-availability-service
      sonar_token_secret_name: SONAR_TOKEN_AVAILABILITY_SERVICE
    secrets: inherit
