name: Frontend Pipeline

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/**"
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/**"
  workflow_dispatch:

concurrency:
  group: medicojob-frontend-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/ci_service_pipeline.yml
    with:
      service_name: frontend
      service_path: frontend
      sonar_project_key: ${{ vars.SONAR_PROJECT_KEY_FRONTEND || vars.SONAR_PROJECT_KEY }}
    secrets: inherit
