name: Medicojob CI Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: medicojob-pr-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  frontend:
    name: Frontend
    uses: ./.github/workflows/ci-frontend.yml
    secrets: inherit

  api-gateway:
    name: API Gateway
    needs: frontend
    uses: ./.github/workflows/ci-api-gateway.yml
    secrets: inherit

  user-service:
    name: User Service
    needs: api-gateway
    uses: ./.github/workflows/ci-user-service.yml
    secrets: inherit

  job-service:
    name: Job Service
    needs: api-gateway
    uses: ./.github/workflows/ci-job-service.yml
    secrets: inherit

  matching-service:
    name: Matching Service
    needs: api-gateway
    uses: ./.github/workflows/ci-matching-service.yml
    secrets: inherit

  availability-service:
    name: Availability Service
    needs: api-gateway
    uses: ./.github/workflows/ci-availability-service.yml
    secrets: inherit

  location-service:
    name: Location Service
    needs: api-gateway
    uses: ./.github/workflows/ci-location-service.yml
    secrets: inherit

  reputation-service:
    name: Reputation Service
    needs: api-gateway
    uses: ./.github/workflows/ci-reputation-service.yml
    secrets: inherit
